image: node:latest

cache:
  paths:
    - node_modules/

# Utilize web identity federation to allow AWS to perform STS calls on our behalf
.aws-prep: &aws-prep
  - | 
    IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"
    mkdir -p ~/.aws
    echo "${AWS_OIDC}" > /tmp/web_identity_token
    echo -e "[profile oidc]\nrole_arn=${GITLAB_ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  environment: production
  id_tokens:
    AWS_OIDC:
      aud: https://gitlab.com
  before_script:
    - *aws-prep
  script:
    - |
      aws s3 ls
      echo "Deploying to production!"
