cache:
  paths:
    - lambda-src/dist/
    - lambda-src/node_modules/
    - cdk/node_modules/

# Utilize web identity federation to allow AWS to perform STS calls on our behalf
.aws-prep: &aws-prep
  - mkdir -p ~/.aws
  - echo "${AWS_OIDC}" > /tmp/web_identity_token
  - echo -e "[profile oidc]\nrole_arn=${GITLAB_ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
  - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${GITLAB_ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${AWS_OIDC}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))

build_lamda_zip:
  stage: build
  image: node:latest
  script:
    - uname -a
    - cd lambda-src
    - npm ci
    - cd ../cdk
    - npm ci
    - npm run build

deploy:
  stage: deploy
  image: docker.io/andysturrock/node_plus_aws_cli
  environment: production
  id_tokens:
    AWS_OIDC:
      aud: https://gitlab.com
  before_script:
    - *aws-prep
  script:
    - echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - cd cdk
    - npm install -g aws-cdk
    - cdk deploy --profile=oidc --require-approval=never --all
