cache:
  paths:
    - node_modules/

# Utilize web identity federation to allow AWS to perform STS calls on our behalf
.aws-prep: &aws-prep
  - |
    mkdir -p ~/.aws
    echo "${AWS_OIDC}" > /tmp/web_identity_token
    echo -e "[profile oidc]\nrole_arn=${GITLAB_ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

build_lamda_zip:
  stage: build
  image: node:latest
  script:
    - ls -lRt

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  environment: production
  id_tokens:
    AWS_OIDC:
      aud: https://gitlab.com
  before_script:
    - *aws-prep
  script:
    - export
    - ls -lrt ~/.aws/config
    - cat ~/.aws/config
    - cat /tmp/web_identity_token
    - aws s3 ls --profile=oidc
    - aws sts get-caller-identity --profile=oidc
    - echo "Deploying to production!"
