cache:
  paths:
    - lambda-src/dist/
    - lambda-src/node_modules/
    - cdk/node_modules/

# Utilize web identity federation to allow AWS to perform STS calls on our behalf
.aws-prep: &aws-prep
  - |
    mkdir -p ~/.aws
    echo "${AWS_OIDC}" > /tmp/web_identity_token
    echo -e "[profile oidc]\nrole_arn=${GITLAB_ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

build_lamda_zip:
  stage: build
  image: node:latest
  script:
    - cd lambda-src
    - pwd
    - npm ci
    - cd ../cdk
    - pwd
    - npm ci
    - npm run build

deploy:
  stage: deploy
  image: node:latest
  environment: production
  id_tokens:
    AWS_OIDC:
      aud: https://gitlab.com
  before_script:
    - *aws-prep
  script:
    - cd cdk
    - cdk deploy --require-approval=never --all --profile=oidc
