import {ConfidentialClientApplication, RefreshTokenRequest} from '@azure/msal-node';
import {aadScopes} from './aadConfig';
import {deleteAADToken} from './tokenStorage';
import {AuthProviderCallback, Client, Options} from '@microsoft/microsoft-graph-client';
import {MeetingOptions} from './parseMeetingArgs';
import {getChannelMembers} from './slackAPI';

export async function createOutlookCalendarMeeting(confidentialClientApplication: ConfidentialClientApplication,
  refreshToken: string, slackUserId: string, channelId: string, meetingOptions: MeetingOptions, timeZone: string, meetingUrl: string) {
  
  const refreshTokenRequest: RefreshTokenRequest = {
    scopes: aadScopes,
    refreshToken: refreshToken
  };
  const authenticationResult = await confidentialClientApplication.acquireTokenByRefreshToken(refreshTokenRequest);

  if(!authenticationResult) {
    // Something has gone wrong so delete the token which will allow the user to login again.
    await deleteAADToken(slackUserId);
    throw new Error("Failed to get new access token from refresh token");
  }

  const channelMembers = await getChannelMembers(channelId);
  type Attendee = {
    emailAddress: {
      address: string
    },
    type: 'required' | 'optional'
  };
  const attendees: Attendee[] = [];
  for(const channelMember of channelMembers) {
    attendees.push({
      emailAddress: {
        address: channelMember.email
      },
      type: 'required'
    });
  }

  const options: Options = {
    authProvider: function (done: AuthProviderCallback): void {
      done("Authentication error", authenticationResult.accessToken);
    }
  };
  const client = Client.init(options);

  const content = `
  <p>Autogenerated meeting from /meet</p>
  <a href="${meetingUrl}">Join here</a> or copy ${meetingUrl} to your browser.
  `;
  const event = {
    subject: `${meetingOptions.name}`,
    body: {
      contentType: 'HTML',
      content
    },
    start: {
      dateTime: meetingOptions.startDate.toISOString(),
      timeZone
    },
    end: {
      dateTime: meetingOptions.endDate?.toISOString(),
      timeZone
    },
    location: {
      displayName: 'GMeet'
    },
    attendees,
    allowNewTimeProposals: false
  };

  await client.api("/me/events").post(event);
}
